// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mission4.Models;

namespace Mission4.Migrations
{
    [DbContext(typeof(MoviesContext))]
    partial class MoviesContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.22");

            modelBuilder.Entity("Mission4.Models.MoviesCategoryModel", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .HasColumnType("TEXT");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            Category = "Action/Adventure"
                        },
                        new
                        {
                            CategoryId = 2,
                            Category = "Comedy"
                        },
                        new
                        {
                            CategoryId = 3,
                            Category = "Drama"
                        },
                        new
                        {
                            CategoryId = 4,
                            Category = "Family"
                        },
                        new
                        {
                            CategoryId = 5,
                            Category = "Horror/Suspense"
                        },
                        new
                        {
                            CategoryId = 6,
                            Category = "Miscellaneous"
                        },
                        new
                        {
                            CategoryId = 7,
                            Category = "Television"
                        },
                        new
                        {
                            CategoryId = 8,
                            Category = "VHS"
                        });
                });

            modelBuilder.Entity("Mission4.Models.MoviesModel", b =>
                {
                    b.Property<int>("MovieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Edited")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Lent_To")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT")
                        .HasMaxLength(25);

                    b.Property<string>("Rating")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Year")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("MovieId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Responses");

                    b.HasData(
                        new
                        {
                            MovieId = 1,
                            CategoryId = 1,
                            Director = "Joss Whedon",
                            Edited = false,
                            Rating = "PG-13",
                            Title = "The Avengers",
                            Year = "2012"
                        },
                        new
                        {
                            MovieId = 2,
                            CategoryId = 2,
                            Director = "Adam McKay",
                            Edited = false,
                            Rating = "PG-13",
                            Title = "Anchorman",
                            Year = "2004"
                        },
                        new
                        {
                            MovieId = 3,
                            CategoryId = 3,
                            Director = "Danny Boyle",
                            Edited = false,
                            Rating = "R",
                            Title = "127 Hours",
                            Year = "2010"
                        });
                });

            modelBuilder.Entity("Mission4.Models.MoviesModel", b =>
                {
                    b.HasOne("Mission4.Models.MoviesCategoryModel", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
